### ISSUE TITLE
Implement requestItem action

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/stacks-service#54] opened 2019-12-02 11:49 UTC
https://github.com/wellcometrust/wellcomecollection.org/blob/master/catalogue/webapp/components/WorkItemsStatus/WorkItemsStatus.js#L59

**Comment by kenoir** [comment] 2019-12-05 14:54
possible dupe of https://github.com/wellcomecollection/stacks-service/issues/52

**Closed as completed by kenoir** 2019-12-05 14:54 UTC
